//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int Department_id { get; set; }
        public string name { get; set; }
        public int Student_id { get; set; }
        public int Doctor_id { get; set; }
        public int Team_id { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Student Student { get; set; }
        public virtual Team Team { get; set; }
    }
}
