//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int Event_id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Sponsor_id { get; set; }
    
        public virtual Sponsor Sponsor { get; set; }
    }
}
