//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        public int Filed_id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Student_id { get; set; }
        public Nullable<int> Doctot_id { get; set; }
        public Nullable<int> Team_id { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Student Student { get; set; }
        public virtual Team Team { get; set; }
    }
}
